### PR TITLE
Add bin/ entry to root-.gitignore and remove now obsolete .gitignore

### PR DESCRIPTION
**Pull request by HannesWell**

### CODE REVIEW

**Comment by HannesWell** [comment]
Maybe it would be better to exclude `.gitignore` files from build-timestamp computation in the platform-parent pom.xml?

**Comment by akurtakov** [comment]
@HannesWell do you plan to do the change in releng parent pom?

**Comment by HannesWell** [comment]
> @HannesWell do you plan to do the change in releng parent pom?

Yes plan to do that sunday/next week when back from vacation.

**Comment by HannesWell** [comment]
> > @HannesWell do you plan to do the change in releng parent pom?
> 
> Yes plan to do that sunday/next week when back from vacation.

Done in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/447

**Pull request merged**
