### PR TITLE
[DO NOT MERGE - TESTING] Update Jenkinsfile

### PR DESCRIPTION
**Pull request by laeubi**
Try with clean m2repository

** DO NOT MERGE **

This is just for testing purpose!

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov @mickaelistria why are ther **two** jenkins build triggered?

**Comment by mickaelistria** [comment]
> why are ther two jenkins build triggered?

Because you created the topic branch in the "upstream" p2 repo (and that's not recommended). Please use your own fork for that instead.

**Comment by laeubi** [comment]
> Please use your own fork for that instead.

Last time I checked this the `Jenkinsfile` was taken/replaced by the "original" branch (for security reasons).

**Comment by mickaelistria** [comment]
> Last time I checked this the Jenkinsfile was taken/replaced by the "original" branch (for security reasons).

This usually depends on whether you're a committer or not. Can you please share a link to this case?

**Comment by laeubi** [comment]
Jenkins discards old builds quickly I'll retry next time then.

**Comment by laeubi** [comment]
> This usually depends on whether you're a committer or not

Could also be that I do not have commit rights at that time.

**Pull request closed without merging**
