### PR TITLE
Remove blank Javadoc

### PR DESCRIPTION
**Pull request by jukzi**
This commit cleans up Javadoc that does not add information. It resolves ecj warnings:
 `Javadoc: Description expected after ...`
It helps to prevent future empty javadoc by disabling missingJavaDoc warnings. This resolves
 `Javadoc: Missing ...`

The modification is a result of regular expression search&replace:

in files `*.java`
 `^[\s]*\*[\s]*(@return|@param[\s]*[^\s]+|@throws[\s]*[^\s]+)\R([\s]*\*[\s]*@|[\s]*\*/\R)`
 ->`$2`
 `^([\s]*\*[\s]*\R)([\s]*\*/\R)`
 ->`$2`
 `^[\S\t ]*/\*\*\R[\s]*\*/\R`
 ->``

in files `org.eclipse.jdt.core.prefs`
 `org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc(Comments|Tags)\=[^\s]*`
 ->`org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc$1\=ignore`

### CODE REVIEW

**Comment by jukzi** [comment]
The build failed with wrong API error messages:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.4-SNAPSHOT:verify (verify) on project org.eclipse.equinox.p2.ui: There are API errors:
[ERROR] src/org/eclipse/equinox/p2/ui/AcceptLicensesWizardPage.java:49 The type org.eclipse.equinox.p2.ui.AcceptLicensesWizardPage has been removed from org.eclipse.equinox.p2.ui_2.8.200
[ERROR] src/org/eclipse/equinox/p2/ui/ICopyable.java:25 The type org.eclipse.equinox.p2.ui.ICopyable has been removed from org.eclipse.equinox.p2.ui_2.8.200
...
```

**Comment by laeubi** [comment]
@jukzi have you checked the the generated javadoc is still correct? I have the feeling that even though empty these end up in the generated doc while now e.g. `@throws` removed it might no longer show the exceptions thrown there.

Also silencing a valid warning seems odd to me, because now I would expect a warning that the param/return/whatever is missing ...

**Comment by jukzi** [comment]
> @jukzi have you checked the the generated javadoc is still correct?

I hope this proves enough:
image

When a parameter is not listed in the javadoc it is added automatically. If instead the parameter is listed in the javadoc but the description is missing it's an error. There is no point in adding an parameter to javadoc without adding a description. Optimally one would describe the parameter but there is nobody that does that for ages

**Comment by laeubi** [comment]
> When a parameter is not listed in the javadoc it is added automatically.

Great, then this looks fine, but we need a green build here whether or not is it considered "valid", you can use the offending bundle and strip it down like I did with the pde.build bundle:

https://github.com/eclipse-tycho/tycho/commit/c7733ee36a5bab7fc1714bab11aec4e367378ec4

if it is reproducible we can look how to fix that but this realistically will not get into a Tycho release before the 2023-12 release ...

**Comment by jukzi** [comment]
> eclipse-tycho/tycho@c7733ee

@laeubi i do not understand a single line of that commit. Can you help please? The jenkins build is constantly failing with the same false positive API errors
https://ci.eclipse.org/equinox/job/p2/job/PR-382/3/console
https://ci.eclipse.org/equinox/job/p2/job/PR-382/4/console

**Comment by laeubi** [comment]
You copy the offending project to https://github.com/eclipse-tycho/tycho/tree/master/tycho-its/projects/api-tools/embedded-jars

then add it to the `pom.xml` as a module

Next you download the baseline jar from the previous release here https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/02aa3dcd09c79bc68c19ba898770f1550e92b85c/eclipse-platform-parent/pom.xml#L143

and add it to the "baseline repo": https://github.com/eclipse-tycho/tycho/tree/master/tycho-its/repositories/api-tools (remove all requirements from the p2 unit as it is not needed/wanted)

then you run 

- `mvn clean install -DskipTests -T1C`
- cd into `tycho-its`
- `mvn clean install -Pits -Dtest=org.eclipse.tycho.test.apitools.ApiToolsTest`

and should see the test fails with the same error in Jenkins

**Comment by laeubi** [comment]
By the way I think this is mostly caused by p2 projects are missing 

`output.. = bin/`

in the build properties, no clue why that is left out (maybe its the default in PDE?!?)

**Comment by jukzi** [comment]
That is beyond my skills. I have 0 knowledge of maven, tycho, poms, baselines etc , all i know is the errors are wrong. - i did not change the API

**Comment by jukzi** [comment]
> By the way I think this is mostly caused by p2 projects are missing
> 
> `output.. = bin/`
> 
> in the build properties, no clue why that is left out (maybe its the default in PDE?!?)

if you know whats wrong could you please fix it?

**Comment by laeubi** [comment]
> > By the way I think this is mostly caused by p2 projects are missing
> > `output.. = bin/`
> > in the build properties, no clue why that is left out (maybe its the default in PDE?!?)
> 
> if you know whats wrong could you please fix it?

Just open build properties of project with error and add it there, then push and see if it helps ...

**Comment by jukzi** [comment]
> Just open build properties of project with error and add it there, then push and see if it helps ...

any chance to fix tycho (or whatever) to use org.eclipse.jdt.internal.core.JavaProject.defaultOutputLocation()? or even hardcode "bin" as for example in org.eclipse.jdt.internal.junit.launcher.JUnitRuntimeClasspathEntry.developmentModeEntry()? The constant seems to be used so often that it can not be changed anyway

**Comment by jukzi** [comment]
build passed

**Pull request merged**
