### PR TITLE
remove Exceptions not actually thrown

### PR DESCRIPTION
**Pull request by jukzi**
eliminates problem markers and dead code

### CODE REVIEW

**Comment by jukzi** [comment]
review/ submit any committer, please?

**Comment by merks** [comment]
@jukzi  Such removals are only acceptable **assuming** no one has overridden the method, right?

**Comment by jukzi** [comment]
> @jukzi Such removals are only acceptable **assuming** no one has overridden the method, right?

yes. if someone in my workspace had overriden it it would have been resulted in an error. As private packages they should not be used outside.

**Comment by jukzi** [comment]
thanks, ed

**Pull request merged**
