### PR TITLE
Comparator error with CachingArtifactRepository in build I20230915-0520

### PR DESCRIPTION
**Pull request by iloveeclipse**
Side effect from c43af59 / https://github.com/eclipse-equinox/p2/pull/314

Fixes https://github.com/eclipse-equinox/p2/issues/320

### CODE REVIEW

**Comment by akurtakov** [comment]
I'll fire new I-build so we get some build pushed.

**Comment by HannesWell** [comment]
Thanks Andrey for the fix.

I wonder why this didn't show up in the verification build?

**Comment by iloveeclipse** [comment]
> I wonder why this didn't show up in the verification build?

I believe such errors are reported only on official build, must be one of maven / jenkins build arguments

**Comment by HannesWell** [comment]
Ok, in m2e I've seen such errors
Probably we have it enabled there and I assumed it is also done in Platform verification builds.

**Pull request merged**
