### PR TITLE
set UTF-8 encoding

### PR DESCRIPTION
**Pull request by jukzi**
solves "Project '' has no explicit encoding set"

### CODE REVIEW

**Comment by merks** [comment]
@laeubi @jukzi 

It seems pretty much everything is failing.  Some do appear to be related, e.g., this is probably because the jgit stamp changes but there are no other changes:
```
Error:  Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.5:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.equinox.p2.garbagecollector: Only qualifier changed for (org.eclipse.equinox.p2.garbagecollector/1.3.100.v20240131-1530). Expected to have bigger x.y.z than what is available in baseline (1.3.100.v20230630-1506) -> [Help 1]
```

The javadoc looks to be in pretty bad shape.  😱 

https://ci.eclipse.org/equinox/job/p2/job/PR-441/1/console

But even here, the overall failures are from baseline comparison problems that @jukzi will need to fix...

**Comment by merks** [comment]
Was it intentional that you added a commit rather than amending and force pushing?

**Comment by jukzi** [comment]
> Was it intentional that you added a commit rather than amending and force pushing?

yes, some people prefer to have version bump in separate commit to make revert easier.

**Comment by jukzi** [comment]
`[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:4.0.5:archive-products (archive-products) on project org.eclipse.equinox.p2.reconciler: Error packing product: Problem creating zip: Execution exception: Java heap space -> [Help 1]`

without commit rights i can not restart jenkins job

**Comment by merks** [comment]
I can kick it, but sometimes for projects where I cannot, I just force push a tiny change to the commit comment.

**Comment by merks** [comment]
It was just some failure at the end packaging something that we don't need for anything.

**Pull request merged**
