### PR TITLE
Workaround for Jenkins builds failing with "Java heap space" errors

### PR DESCRIPTION
**Pull request by iloveeclipse**
Fixes https://github.com/eclipse-equinox/p2/issues/463

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@laeubi : no idea what is wrong, but maven seem to read JVM argument as maven option:

```
Error:  Error executing Maven.
org.apache.commons.cli.ParseException: Unrecognized maven.config file entries: [mx2g]
```

**Comment by mickaelistria** [comment]
I think you mean Jenkins, not Gerrit.

**Comment by iloveeclipse** [comment]
> I think you mean Jenkins, not Gerrit.

Doesn't work either.

**Comment by akurtakov** [comment]
"Please add https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.mvn/jvm.config to this repository as well, it should help with that OOM errors as currently only 1GB of 4G is used by default." but you put it in maven.config. It's well documented and explained in https://maven.apache.org/configure.html .

**Comment by iloveeclipse** [comment]
> "Please add https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.mvn/jvm.config to this repository as well, it should help with that OOM errors as currently only 1GB of 4G is used by default." but you put it in maven.config. It's well documented and explained in https://maven.apache.org/configure.html .

I'm allowed to make mistakes, OK?

**Comment by akurtakov** [comment]
> > "Please add https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.mvn/jvm.config to this repository as well, it should help with that OOM errors as currently only 1GB of 4G is used by default." but you put it in maven.config. It's well documented and explained in https://maven.apache.org/configure.html .
> 
> I'm allowed to make mistakes, OK?

Sure, that's why I point you to the detailed documentation for reference in the future.

**Pull request merged**
