### PR TITLE
Require httpclientjava instead of httpclient5

### PR DESCRIPTION
**Pull request by laeubi**
Fix https://github.com/eclipse-equinox/p2/issues/205

### CODE REVIEW

**Review by akurtakov — COMMENTED** [review]
The change looks good but I haven't tested it at all. I am pretty sure that the only way for this to be thoroughly tested is via I-build though.

**Comment by laeubi** [comment]
> The change looks good but I haven't tested it at all. I am pretty sure that the only way for this to be thoroughly tested is via I-build though.

Yes I'm also not sure how P2 will behave here... as it is only a prerequisite and not a (strict) requirement  it might just install the new connector additionally?

I think if the test suceed, we can merge and must see what happens...

**Comment by vogella** [comment]
AFAIK testing p2 from a runtime Eclipse is not really possible so +1 for merging to see it used in an I-build (if the validation build is green).

**Comment by laeubi** [comment]
Seems it is not that easy... have to investigate further, but if someone else likes to take a look help would be welcome.

**Review by merks — APPROVED** [review]
I was able to install a feature (EMFs SDK feature) in a self-hosted runtime where software installation is enabled.  So it appears to work well for me.

**Comment by merks** [comment]
Note that in my self-host launch running the org.eclipse.sdk.ide product, the following ECF bundles are installed:

image

**Comment by vogella** [comment]
Time to merge this one?

**Review by vogella — APPROVED** [review]
+1 for merging to see this in a running IDE. If we face issues we still can revert

**Comment by HannesWell** [comment]
> +1 for merging to see this in a running IDE. If we face issues we still can revert

I cannot assess the change, but if it is risky then we should it better sooner than later.

**Comment by akurtakov** [comment]
It needs someone to sign up to keep an eye on it and it has to go for M1 if at all. I can land a hand but can't be the driving force here. So if someone feels like it today is the day or it would miss yet another release.

**Comment by laeubi** [comment]
I have rebased the change now, but I won't have time too look into the testfailures or give dedicated support for it.

**Comment by iloveeclipse** [comment]
> It needs someone to sign up to keep an eye on it and it has to go for M1 if at all. I can land a hand but can't be the driving force here. So if someone feels like it today is the day or it would miss yet another release.

I can watch for issues, and offer to revert it ASAP if needed :-)

**Comment by merks** [comment]
It looks like all the builds so far are aborting:

https://ci.eclipse.org/equinox/job/p2/job/PR-206/

> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:4.0.0-SNAPSHOT:test (default-test) on project org.eclipse.equinox.p2.tests: An unexpected error occurred while launching the test runtime (process returned error code 143(SIGTERM received?)). 

Without timestamps in the log, one can't really tell which parts are taking so long, but each seems to abort during the p2 tests...

Normal builds appear to take about 20 minutes:

https://ci.eclipse.org/equinox/job/p2/job/master

Similarly the p2 action build is taking very long:

image

While a normal such build should take about 15 minutes:

image

Something is either very slow or non-terminating...

**Comment by laeubi** [comment]
Yes I assume some test is waiting for "something" to happen and then blocks forever, but I haven't had time yet to investigate this.

**Comment by akurtakov** [comment]
I would be very happey if this one lands in now. @laeubi do you plan to do so?

**Comment by laeubi** [comment]
I have rebased the change lets see what happens but last time the tests started to hang infinite...

**Comment by laeubi** [comment]
One of the test fail here:

```
org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at https://download.eclipse.org/eclipse/updates/4.21/R-4.21-202109060500/content.xml.xz.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCacheFromFile(CacheManager.java:132)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.getLocalFile(XZedSimpleMetadataRepositoryFactory.java:60)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.load(XZedSimpleMetadataRepositoryFactory.java:80)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:63)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:787)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:685)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.equinox.p2.tests.metadata.repository.MetadataRepositoryManagerTest.testMetadataCachingRemoteRepo(MetadataRepositoryManagerTest.java:396)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at org.eclipse.equinox.p2.tests.AbstractProvisioningTest.runTest(AbstractProvisioningTest.java:968)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.api.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:137)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:148)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:88)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:140)
	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.start(HeadlessTestApplication.java:29)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.io.IOException: Invalid last modified value
	at org.eclipse.ecf.provider.filetransfer.httpclientjava.HttpClientFileSystemBrowser.getLastModifiedTimeFromHeader(HttpClientFileSystemBrowser.java:335)
	at org.eclipse.ecf.provider.filetransfer.httpclientjava.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:277)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

The URl in question returns `Last-Modified: Sat, 16 Mar 2019 16:14:09 GMT` but the string looks fine for me...

**Comment by akurtakov** [comment]
Sounds like something to be improved in ecf httpclient  .

**Comment by laeubi** [comment]
I have created
- https://github.com/eclipse/ecf/pull/48

so it should work with an english locale, when execute the build I get some more errors that seem to be related to locales (but not to the transport) that is a bit unfortunate as it seems that

1. tests assume a certain locale to succeed
2. some test fail with a different locale so we can't really test with different ones...

**Comment by laeubi** [comment]
I fear we need a new ECF release first before we can proceed here but, It would be good if someone else could also execute the build locally (a simple `mvn clean verify` should suffice) and check if they see any other issues yet.

**Comment by laeubi** [comment]
Thanks to @scottslewis for merging the fix, I now was able to reproduce the hang locally, the test loops for ever here:

```
"main" #1 prio=5 os_prio=0 cpu=12359,17ms elapsed=1675,59s tid=0x00007f3b640266e0 nid=0x1408 waiting on condition  [0x00007f3b6be52000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@17.0.6/Native Method)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.waitPaused(FileReader.java:416)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.readInto(FileReader.java:389)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:136)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact(SimpleArtifactRepository.java:734)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact(SimpleArtifactRepository.java:656)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact(SimpleArtifactRepository.java:793)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.getArtifact(MirrorRequest.java:329)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transferSingle(MirrorRequest.java:299)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transfer(MirrorRequest.java:232)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.perform(MirrorRequest.java:162)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact(SimpleArtifactRepository.java:775)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifacts(SimpleArtifactRepository.java:855)
	at org.eclipse.equinox.internal.p2.engine.DownloadManager.fetch(DownloadManager.java:127)
	at org.eclipse.equinox.internal.p2.engine.DownloadManager.start(DownloadManager.java:98)
	at org.eclipse.equinox.internal.p2.engine.phases.Collect.completePhase(Collect.java:124)
	at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
	at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
	at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:95)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:49)
	at org.eclipse.equinox.p2.tests.engine.PhaseSetTest.doProvisioning(PhaseSetTest.java:235)
	at org.eclipse.equinox.p2.tests.engine.PhaseSetTest.basicTest(PhaseSetTest.java:201)
	at org.eclipse.equinox.p2.tests.engine.PhaseSetTest.testPauseAndResumeMoreThanOnce(PhaseSetTest.java:287)
```

**Comment by laeubi** [comment]
@scottslewis can you probabbly help out here or give a hint? I tracked this down to  `org.eclipse.equinox.internal.p2.transport.ecf.FileReader.waitPaused(FileReader.java:416)` never returning because it seems it waits for an event that never happens.

**Comment by scottslewis** [comment]
> @scottslewis can you probabbly help out here or give a hint? I tracked this down to `org.eclipse.equinox.internal.p2.transport.ecf.FileReader.waitPaused(FileReader.java:416)` never returning because it seems it waits for an event that never happens.

I'm not the author of the p2.transport code, so I'm coming into this as cold as others are.   The ECF test cases do not show this hang with the javahttpclient. 

I will get the FileReader code and look for myself.  But some questons for those that might be more knowlegeable

Please describe the expected behavior of whatever p2 test code resulted in the waitPaused being executed?  i.e. what event is it waiting for?

What are the p2 test(s) that show this hang?   Do they have any similarities in semantics?

Are there other tests that do similar things to the ones that fail but pass?

**Comment by laeubi** [comment]
> The ECF test cases do not show this hang with the javahttpclient.

I must confess that I'm even not quite sure how useful pause/resume is and if it is actually used in ECF so it might be that this is P2 specific but I have no idea if it is of any use there as I never noticed that but @merks might know better here. So one solution would maybe to just drop pause/resume.

> Please describe the expected behavior of whatever p2 test code resulted in the waitPaused being executed? i.e. what event is it waiting for?

As far as I understand there is the method `org.eclipse.equinox.internal.p2.transport.ecf.FileReader.handleTransferEvent(IFileTransferEvent)` where it handles different kinds of ECF events like `IIncomingFileTransferReceivePausedEvent` and `IIncomingFileTransferReceiveResumedEvent`

**Comment by merks** [comment]
I'm not actually sure how pause/resume is used in the IDE.  I've never used it and I'm not sure how one uses it from the IDE or an application.  Is this problem reproducible with a debug launch of the/a test case?

**Comment by scottslewis** [comment]
> > The ECF test cases do not show this hang with the javahttpclient.
> 
> I must confess that I'm even not quite sure how useful pause/resume is and if it is actually used in ECF so it might be that this is P2 specific but I have no idea if it is of any use there as I never noticed that but @merks might know better here. So one solution would maybe to just drop pause/resume.

It's possible that the javahttpclient provider didn't implement ECF filetransfer API pause/resume fully/correctly and that is why this test is failing.   That would be the first place I would (will) look...i.e. the javahttpclient provider pause/resume (i.e. compared to httpclient5 impl).

But I do want to also verify that this test is using pause/resume to make sure.

Even if Eclipse isn't actually using filetransfer pause/resume, the provider should have a functioning impl as it's in the API.

> 
> > Please describe the expected behavior of whatever p2 test code resulted in the waitPaused being executed? i.e. what event is it waiting for?
> 
> As far as I understand there is the method `org.eclipse.equinox.internal.p2.transport.ecf.FileReader.handleTransferEvent(IFileTransferEvent)` where it handles different kinds of ECF events like `IIncomingFileTransferReceivePausedEvent` and `IIncomingFileTransferReceiveResumedEvent`

OK.   If someone else knows what event (type) it's waiting for (i.e. from the test context) please say so...I would assume IIncomingFileTransferReceiveResumedEvent based upon above but will have to look at the p2 and test code to see.

**Comment by scottslewis** [comment]
I believe I've found the problem.

This is the isConnected() method from the httpclientjava provider:

`	protected boolean isConnected() {
		return (httpResponse != null && !httpResponse.isCancelled());
	}

`

The isConnected() method is called during the call to pausable.resume(), and if isConnected() returns true then the resume() call returns false (because it can't/shouldn't resume unless isConnected() returns false.

The problem seems to be that in the httpclientjava provider, after pausing the httpResponse is non-null *and* httpResponse.isCancelled() returns *false* (meaning that isConnected() returns true.   This ends up confusing the p2 FileReader code because it doesn't look at the value returned from pausable.resume()...and assumes the resume was successful...and so waits forever for things to complete.

I don't know why httpResponse.isCancelled() returns false.   It could be a bug, or it could be something about httpResponse.cancel(true) getting called multiple times/multiple threads by hardClose() that causes it to do this.   But for whatever reason after pause and before resume isCancelled() is returning false and isConnected() is returning true.  isConnected() should be returning false when after pause and before resume.

In the httpclient5 provider, isConnected() returns false between pause() and resume() and the pause/resume works correctly.

The fix for this should be simple...e.g. it might be putting httpResponse = null in hardClose after httpResponse.cancel(true).  I tested this fix and it does fix things, but I'm going to ask @laeubi to determine what the correct fix is as I'm not sure whether httpResponse must be non-null for some other reason in the httpclientjava provider.

**Comment by laeubi** [comment]
Many thanks for looking into this!

>  This ends up confusing the p2 FileReader code because it doesn't look at the value returned from pausable.resume()...and assumes the resume was successful...and so waits forever for things to complete.

Can you create a bug (and probably even suggest a fix, e.g throwing a useful exception?)

> The problem seems to be that in the httpclientjava provider, after pausing the httpResponse is non-null and httpResponse.isCancelled() returns false (meaning that isConnected() returns true.

It could be that the connection is actually done at this point of time, I'm not quite sure whats the purpose of isconnected, but maybe it should simply be `!httpResponse.isDone()` (what would mean either successful, canceled or failed) ...

**Comment by scottslewis** [comment]
> Many thanks for looking into this!
> 
> > This ends up confusing the p2 FileReader code because it doesn't look at the value returned from pausable.resume()...and assumes the resume was successful...and so waits forever for things to complete.
> 
> Can you create a bug (and probably even suggest a fix, e.g throwing a useful exception?)

I've created this p2 issue:  https://github.com/eclipse-equinox/p2/issues/300

Since I don't know the p2 ecf transport code at all I can't immediately suggest a fix (it depends upon the context of when/how p2 is calling pause and resume).

> 
> > The problem seems to be that in the httpclientjava provider, after pausing the httpResponse is non-null and httpResponse.isCancelled() returns false (meaning that isConnected() returns true.
> 
> It could be that the connection is actually done at this point of time, I'm not quite sure whats the purpose of isconnected, but maybe it should simply be `!httpResponse.isDone()` (what would mean either successful, canceled or failed) ...

Happily isConnected() is only called in doPause() and doResume()...which are both declared in abstract class and implemented in all the providers.   You can remove isConnected() from the httpclientjava file transfer impl class if you want.   However, you should probably do something about the doPause() and doResume() impls in httpclientjava (other than simply remove isConnected) so that they return false if they are called when the filetransfer instance is not in the correct state (which is why they call isConnected() now).

Also...just to be aware, in multi-threaded/job context it is possible to have hardClose() called more than once...so any cleanup that's in there should be prepared to handle that (currently the httpResponse.cancel(true) is/can be called multiple times.

**Comment by laeubi** [comment]
> I've created this p2 issue: https://github.com/eclipse-equinox/p2/issues/300

Thanks!

> Happily isConnected() is only called in doPause() and doResume()...which are both declared in abstract class and implemented in all the providers. You can remove isConnected() from the httpclientjava file transfer impl class if you want. However, you should probably do something about the doPause() and doResume() impls in httpclientjava

Maybe if no one has a clue what it is useful for one might simply not adapt to that interface at all? From the code I think this will equally block the test, but maybe we should simply remove pause/resume from p2 at all WDYT @merks ?

**Comment by merks** [comment]
As I asked in https://github.com/eclipse-equinox/p2/pull/206#issuecomment-1621605135
 can the failure be reproduced launching in the IDE?  I.e., which test is hanging?  

In general it is of course seems better to test that the new version is a good drop-in replacement and to figure out why that's not the case when/if that's not the case.   Me being clueless about something is as much an argument to get clued in as it is to remove that something.  😜   Also, it will be good for me to test the impact of this on Oomph as well while I am at it...

I'll do some digging today...

**Comment by laeubi** [comment]
I can reproduce it with a local maven build, I don't know from the IDE as then one somehow must use the local build artifact with my recent fix there somehow.
I'll try to propose a fix, but if it does not work reliable (especially on the P2 side!) it might be better to remove it, maybe we can make the situation better by fixing, I'll propose a patch soon
- https://github.com/eclipse-equinox/p2/issues/300

**Comment by merks** [comment]
I'm setting up an IDE in which I can also do local testing with Oomph too...

**Comment by merks** [comment]
I can debug launch the test and they do pass locally:

image

I think I will set up a second identical IDE but then pull in this PR's changes so that I can compare how the two function differently.

**Comment by laeubi** [comment]
@merks just in case you are not using English locale you will require this fix from ECF to run the new client:

- https://github.com/eclipse/ecf/pull/48

**Comment by scottslewis** [comment]
> As I asked in [#206 (comment)](https://github.com/eclipse-equinox/p2/pull/206#issuecomment-1621605135) can the failure be reproduced launching in the IDE? I.e., which test is hanging?
> 
> In general it is of course seems better to test that the new version is a good drop-in replacement and to figure out why that's not the case when/if that's not the case. Me being clueless about something is as much an argument to get clued in as it is to remove that something. 😜 Also, it will be good for me to test the impact of this on Oomph as well while I am at it...
> 
> I'll do some digging today...

FWIW, I believe that at one time in the past there was discussion of adding a p2 UI to allow the user to pause and resume/cancel downloads.   IMHO this would be a nice feature for an eclipse 'download manager', and of course would be implemented by pause()/resume() at the ECF level.   

Since I don't remember this discussion, and I wasn't involved in the code (of ecf transport or UI) I would suggest looking at the p2 UI code (and/or enhancements) a little bit to see if there is anything there that maybe could be used to add a pause/resume feature (now or in future) before removing the use of pause/resume from p2 ecf transport code (and the test code).

And...in any case I still need fix for the httpclientjava provider so that it functions as per api.  I'll leave it up to @laeubi to decide on proper fix and whether this warrants a new issue.

**Comment by scottslewis** [comment]
Thanks to @merks for providing fix for httpclientjava impl of isConnected().    I've made necessary version+feature updates and some small simplifications.  This fix has been merged and version 3.14.40 snapshot of ECF can be found for testing here:  

https://download.eclipse.org/rt/ecf/snapshot

**Comment by scottslewis** [comment]
@merks  ping.   I've merged the fix from you at

https://github.com/eclipse/ecf/pull/54

tested via ECF filtransfer tests, and it is working properly in 3.14.40

https://download.eclipse.org/rt/ecf/snapshot/site.p2/3.14.40.v20230728-2232/

which is currently in snapshot (3.14.40 of ECF not released yet).

I've been waiting to release 3.14.40 for testing on the platform side as per the test failure that started this issue.   I would like to release ECF 3.14.40 soon so that it can get into 4.29M3...hopefully with eclipse using javahttpclient (and so not having to include 1 meg worth of apache httpclient5 provider...which it is currently doing in 4.29Mx/ECF version 3.14.39.

Before I release 3.14.40 in ECF I would like to ask that someone on platform try out the platform p2 test suite with the snapshot 3.14.40 version linked to above and verify that all the p2 tests pass.   If so, then I'll release ECF 3.14.40, and if platform team agrees then httpclient5 provider can be removed from eclipse in favor of the javahttpclient provider and released as 4.29M3+.   

When that happens I would ask that someone on platform team be identified to help out with regression reports for javahttpclient from milestone builds/releases in case there are any unanticipated problems.

Also:  wrt this issue:  https://github.com/eclipse-equinox/p2/issues/300

Although desirable to have this p2 fix, I don't consider this necessary for use of the java httpclient provider in eclipse/this issue.  But platform/p2 devs can prioritize as desired.

**Comment by laeubi** [comment]
@scottslewis I think platform will go with "old" http5 client for this release, but still an ECF relase with the fixes would be highly desired so we can start as soon as possible on the next cycle with the integration of java11 client!

I think there was just one issue with `GOAWAY` I'm not sure if @merks think something should change in ECF.

**Comment by merks** [comment]
@scottslewis 

Yes, switching versions is something we'd best do at the start of the release cycle, so that we have a long runway to mitigate and problem.  And yes, I had a problem with very rapid HEAD requests for p2's stats collection, but that only caused logging, not an actual failure; I don't think this a problem with the ECF implementation but rather just a bad behavior of the JDK.

FYI, there are **lots** of newer versions of libraries available here:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-09/

Especially lots of the old javax.* bundles have newer jakarta.* bundles as replacement (still exporting javax.* packages).

**Comment by HannesWell** [comment]
Should we try this again now?

**Comment by scottslewis** [comment]
> Should we try this again now?

+1 from me.   ECF 3.14.40 is in snapshot right now at

https://download.eclipse.org/rt/ecf/snapshot/site.p2/3.14.40.v20230905-1933/

with all the fixes requested of ECF so far.   It's passing all our filetransfer tests.

I expect that someone with the ability to make platform changes to use the  javahttpcient provider (e.g. different ECF feature and removed httpclient5 bundles, etc) will make them and run the platform/p2 tests that were hanging before the javahttpclient provider fixes.   

If all p2 tests pass now, then I expect platform can include in integration builds and next milestones and deployment testing can be done.  If problems are found with the javahttpclient provider then whomever needed can fix them and I'll produce a new snapshot build of ECF.   When/if things look stable enough for platform release then I will release ECF 3.14.40 fully and it can be used for later platform release rather than the snapshot build.

The following outstanding issue:  https://github.com/eclipse-equinox/p2/issues/300 is a p2 improvement that I can't make.  It's not strictly required for the javahttpclient provider to work properly, but it would be nice if it was fixed before the deploy of the provider as it would/will prevent the hanging that was seen in tests that started this issue.

**Comment by laeubi** [comment]
We can only include releases not snapshots in the platform build, so if there is no immediate blocker why not simply release the next ECF version right now?

**Comment by mickaelistria** [comment]
> We can only include releases not snapshots in the platform build, 

That is not really true. We can include snapshots for important changes if we need to test them ASAP. What matters is that we do not include snapshots in releases, but snapshots in dev builds or milestones are acceptable (provided they come with a clear and safe plan to not leak into release)

**Comment by laeubi** [comment]
@mickaelistria can you then propose how we use the snapshot build here in the PR?

**Comment by mickaelistria** [comment]
Sorry, I thought you were talking about I-Builds, where it's "just" a matter of changing the .target file.
However, for a PR, we'd need to add some Maven/Tycho magic to the root pom file of the repo: add the `repository` pointing to latest ECF snapshots, and dealing with version constraints in MANIFEST.MF, or p2.inf, or Tycho target-platform-filtes... to force usage of the snapshot for this particular PR build.

**Comment by laeubi** [comment]
adding it as a (temporary) repository seems a good idea, I'll try that out ....

**Comment by laeubi** [comment]
I have rebased, resolved conflict and added the snapshot site as a repository, lets see what happens :-)

**Comment by laeubi** [comment]
Alright we have no longer a hang of the test but one test-failure that looks a bit strange:

https://ci.eclipse.org/equinox/job/p2/job/PR-206/9/testReport/junit/org.eclipse.equinox.p2.tests.artifact.repository/TransferTest/testGZFileAreNotUnzipped/
https://github.com/eclipse-equinox/p2/pull/206/checks?check_run_id=16891673579

**Comment by scottslewis** [comment]
> Alright we have no longer a hang of the test but one test-failure that looks a bit strange:
> 
> https://ci.eclipse.org/equinox/job/p2/job/PR-206/9/testReport/junit/org.eclipse.equinox.p2.tests.artifact.repository/TransferTest/testGZFileAreNotUnzipped/ https://github.com/eclipse-equinox/p2/pull/206/checks?check_run_id=16891673579

This does not appear to me to have anything to do with ECF or the javahttpclient provider.  

>java.lang.NullPointerException: Cannot invoke "org.osgi.framework.Bundle.getSymbolicName()" because "bundle" is null

It seems strange to me that Bundle.getSymbolicName() would ever fail in the Eclipse testing environment but perhaps it's possible under some conditions?

**Comment by laeubi** [comment]
> It seems strange to me that Bundle.getSymbolicName() would ever fail in the Eclipse testing environment but perhaps it's possible under some conditions?

the bundle itself is null so maybe something has changed here where a specific bundle name is assumed, I'll take a look... I just wanted to point out that now tests are all running (even though not passing) that before where blocked forever so that is now fixed :+1:

**Comment by laeubi** [comment]
The problem is this line:

https://github.com/eclipse-equinox/p2/blob/60a4a7ee8d5f15d1c1a7e45406efe12edbe82f63/bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/repository/TransferTest.java#L62C1-L62C7

It seems only a debugline so I'll adjust it, beside that the test seem to reference packed artifacts so probably should be removed at all @akurtakov ?

**Comment by akurtakov** [comment]
The test referes to pack.gz file but this seems to be because this was the first gziped file found convenient. It could actually be any gzipped file.

**Comment by laeubi** [comment]
@vogella  @merks @akurtakov the build now succeeds, I'll leave it up to you to merge this if desired.

**Comment by akurtakov** [comment]
In the current shape there are high chances to fail the build as I'm not sure that all the products will find content from the extra p2 repo added here. 
@scottslewis Would you please release ecf so we can update to it in Platform's target platform?
After new ecf version is in target platform this one would have to be amended and the merge can happen.

**Comment by mickaelistria** [comment]
In the meantime, couldn't we update the .target to use the snapshots of ECF and then merge this patch without the extra repo and keep a ticket open to ensure we update to ECF release ASAP ?

**Comment by akurtakov** [comment]
If the snapshot is here to stay till a release - yes.

**Comment by mickaelistria** [comment]
Looks like the https://download.eclipse.org/rt/ecf/snapshot/site.p2/ contains snapshots which are more than 1 year old, so let's just use it in .target until there is a release ( @scottslewis the sooner the better ;) ).
I'm taking care of the change in .target.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1372 about updating the .target.

**Comment by mickaelistria** [comment]
The ECF snapshot was added to the .target. Can you please amend the commit to remove the repository entry?

**Comment by laeubi** [comment]
Done.

**Comment by mickaelistria** [comment]
Merged. Thanks a lot!
For the moment, I've left httpclient5 part of the .target; I hope we will be able to remove it after next I-Build, or are there any other known client left in Platform?

**Comment by iloveeclipse** [comment]
Would be nice to trigger an I Build now to verify if anything is broken.

**Comment by mickaelistria** [comment]
OK, I'm triggering I-Build.

**Comment by merks** [comment]
> Merged. Thanks a lot! For the moment, I've left httpclient5 part of the .target; I hope we will be able to remove it after next I-Build, or are there any other known client left in Platform?

@mickaelistria if you like, I'll add this cleanup to my TODO list.  I've already done some investigation previously for the impact on Oomph which is also directly using ECF.  Here too the switch is mostly painless...

**Comment by mickaelistria** [comment]
OK, I happily leave it the continuation of the cleanup to you @merks !

**Comment by scottslewis** [comment]
> Looks like the https://download.eclipse.org/rt/ecf/snapshot/site.p2/ contains snapshots which are more than 1 year old, so let's just use it in .target until there is a release ( @scottslewis the sooner the better ;) ). I'm taking care of the change in .target.

I would prefer to wait one week for a full release of ECF, as a full release requires some extra releng that I don't have time for this week.   Also, IMO it would be nice to have one platform integration release for a 'smoke test' of javahttpclient provider (and perhaps more difficult removing the httpclient5 provider and all org.apache.* deps) before I do a release as I don't see doing weekly releases of ECF as feasible for me right now.

It seems that maybe you've already used the latest at https://download.eclipse.org/rt/ecf/snapshot/site.p2/, which is:

https://download.eclipse.org/rt/ecf/snapshot/site.p2/3.14.40.v20230905-1933/

in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1372

**Pull request merged**
