### PR TITLE
Don't attempt to PGP verify folder-based content

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-equinox/p2/issues/374

### CODE REVIEW

**Review by laeubi — APPROVED** [review]
Seems easy and valid to assume, I wonder if the same is true fro checksum verifiers?
Will such content be reported as unsigned afterwards?

**Comment by merks** [comment]
If other verifiers were a problem (i.e., if they failed) we'd have noticed long ago. 😱   Moreover, they are not an issue because those properties are not in the target platform's artifacts.xml.

**Comment by laeubi** [comment]
> they are not an issue because those properties are not in the target platform's artifacts.xml

Should md5 sha256 and alike not be part of artifacts? ...

**Comment by merks** [comment]
In general, artifact properties of the source artifact descriptor are **not transferred** to the target except when doing raw transfers, i.e., when actually mirroring a repository.  For operations such as populating a target platform or installing/updating into an installation, the processing instructions are applied so the target might end up being a folder.  In the past, one would download the pack200 artifact, if available, and unpack200 it to create the jar at the destination.  So in general the checksums are not applicable after the transfer.   Remember well that I had to specialize p2 when PGP signing was introduced to ensure that the PGP signature and key are, unlike the other properties, transferred from source to target in all cases, otherwise the signing information is lost...

**Pull request merged**
